# Import the library

In [2]:
import numpy as np


## 1-D Array

In [3]:
lst = [1,2,3,4,5]
arr = np.array(lst)

In [4]:
arr

array([1, 2, 3, 4, 5])

In [5]:
arr.shape     # 5 columns 1 row

(5,)

## 2-D Array

In [6]:
lst1 = [1,2,3,4,5]
lst2 = [2,4,6,8,10]
lst3 = [3,6,9,12,15]
arr1 = np.array([lst1, lst2, lst3])

In [7]:
arr1

array([[ 1,  2,  3,  4,  5],
       [ 2,  4,  6,  8, 10],
       [ 3,  6,  9, 12, 15]])

In [8]:
arr1.shape

(3, 5)

# Indexing

### Indexing in 1D array

In [9]:
arr

array([1, 2, 3, 4, 5])

In [10]:
print(arr[3]) # 3rd element

4


In [11]:
arr[1:4] # from 1st to 3rd element

array([2, 3, 4])

In [12]:
arr[:]  # Last element

array([1, 2, 3, 4, 5])

In [13]:
arr[2:]  # from 2nd element till last

array([3, 4, 5])

In [14]:
arr[:4]  # From start till 4-1 = 3rd element

array([1, 2, 3, 4])

In [15]:
print(arr[-1]) # Last one

5


In [16]:
arr[:-1] # every on except last one

array([1, 2, 3, 4])

In [17]:
arr[::] #return all element

array([1, 2, 3, 4, 5])

In [18]:
arr[::-1] # returns teh reverse of array

array([5, 4, 3, 2, 1])

In [19]:
arr[::-2] # return the array in reverse order but return element by skipping alternate

array([5, 3, 1])

### Indexing in 2D array

In [20]:
arr1

array([[ 1,  2,  3,  4,  5],
       [ 2,  4,  6,  8, 10],
       [ 3,  6,  9, 12, 15]])

In [21]:
arr1[:,:]  #   arr1[r, c] r = number of rows and c = number of columns

array([[ 1,  2,  3,  4,  5],
       [ 2,  4,  6,  8, 10],
       [ 3,  6,  9, 12, 15]])

In [ ]:
arr1[:, 2]  # This means all the element from  2nd columns

np.int64(6)

In [25]:
arr1[2,:]  #This means all elements of row at 2nd index

array([ 3,  6,  9, 12, 15])

In [ ]:
# we want 4, 6 from 2nd row and 6, 9 from 3rd row
arr1[1:,1:3]

array([[4, 6],
       [6, 9]])

In [ ]:
# we want 8, 10 from 2nd row and 12, 15 from 3rd row
arr1[1:,3:]

array([[ 8, 10],
       [12, 15]])

In [36]:
# we want 1,2,3 from 2nd row and 5, 10, 15 from 3rd row
arr1[:,::4]

array([[ 1,  5],
       [ 2, 10],
       [ 3, 15]])

# EDA point of view

In [37]:
arr

array([1, 2, 3, 4, 5])

In [ ]:
arr[arr<3]   # creates the array of elements lesser than 3 in arr

array([1, 2])

### Reshape the array

In [39]:
arr1

array([[ 1,  2,  3,  4,  5],
       [ 2,  4,  6,  8, 10],
       [ 3,  6,  9, 12, 15]])

In [40]:
arr1.shape

(3, 5)

In [41]:
arr1.reshape(5,3)

array([[ 1,  2,  3],
       [ 4,  5,  2],
       [ 4,  6,  8],
       [10,  3,  6],
       [ 9, 12, 15]])

### Mechanism to create a array

In [44]:
np.arange(1,20, 2)  # np.arange(start, stop, step)

array([ 1,  3,  5,  7,  9, 11, 13, 15, 17, 19])

In [45]:
np.arange(1,20, 2).reshape(2,5)

array([[ 1,  3,  5,  7,  9],
       [11, 13, 15, 17, 19]])

In [46]:
np.arange(1,20, 2).reshape(5,2)

array([[ 1,  3],
       [ 5,  7],
       [ 9, 11],
       [13, 15],
       [17, 19]])

### Operations on array

In [47]:
arr

array([1, 2, 3, 4, 5])

In [ ]:
arr*2 # Adding 2 to each element

array([ 2,  4,  6,  8, 10])

In [ ]:
arr*arr   # multiplying each element by itself

array([ 1,  4,  9, 16, 25])

In [ ]:
arr**arr    # element ^ element

array([   1,    4,   27,  256, 3125])

In [53]:
np.ones((2,3))

array([[1., 1., 1.],
       [1., 1., 1.]])

In [54]:
np.zeros((2,3))

array([[0., 0., 0.],
       [0., 0., 0.]])

In [ ]:
np.random.randint(10, 50) # Initializes any number between 10, 50 

12

In [ ]:
np.random.randint(10, 50, 4) # Initializes any 4 numbers between 10, 50 

array([48, 35, 42, 23], dtype=int32)

In [ ]:
np.random.randn(3,4) 

array([[-0.0279664 ,  0.28665523,  0.32605896,  0.19139662],
       [ 1.49067127,  0.52193528, -0.74000107, -0.1514402 ],
       [-0.66344874, -1.28110638,  0.20163458, -0.28248695]])

In [63]:
np.random.random_sample((3,4)) # includes all the values between 0 to 1

array([[0.41702653, 0.84273619, 0.07227494, 0.33893253],
       [0.82770403, 0.65986179, 0.78908622, 0.79363255],
       [0.5558437 , 0.82936055, 0.5731828 , 0.8358356 ]])