In [1]:
import numpy as np

# Section A

### **A1.** Create a 1D array of numbers from 5 to 50 with a step of 5 using `np.arange`.

In [2]:
np.arange(5, 50, 5)

array([ 5, 10, 15, 20, 25, 30, 35, 40, 45])

### **A2.** Create a 3x3 array of all zeros, then a 2x4 array of all ones.

In [3]:
np.zeros((3,3))

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [5]:
np.ones((2,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.]])

### **A3.** Use `np.linspace` to generate 10 evenly spaced values between 0 and 100 (inclusive).

In [10]:
np.linspace(0, 100, 10)

array([  0.        ,  11.11111111,  22.22222222,  33.33333333,
        44.44444444,  55.55555556,  66.66666667,  77.77777778,
        88.88888889, 100.        ])

### **A4.** Create a 4x4 identity matrix.

In [11]:
np.identity(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

### **A5.** Create a 1D array of 20 random integers between 1 and 100 using `np.random.randint`. Set a seed of `42` first so your output is reproducible.

In [14]:
np.random.seed(42)
np.random.randint(1, 100, 20)

array([52, 93, 15, 72, 61, 21, 83, 87, 75, 75, 88, 24,  3, 22, 53,  2, 88,
       30, 38,  2], dtype=int32)

# Section B


### **B1.** Create a 2D array with shape `(4, 3)` containing numbers 1–12 (hint: use `np.arange` + `.reshape()`). Print its `.shape`, `.ndim`, and `.size`.

In [20]:
arr = np.arange(1,13).reshape(4,3)
print(f"Array :- {arr}")
print(f"Shape :- {arr.shape}")
print(f"N dim :- {arr.ndim}")
print(f"Size :- {arr.size}")

Array :- [[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]
Shape :- (4, 3)
N dim :- 2
Size :- 12


### **B2.** Create a 3D array of shape `(2, 3, 4)` filled with random integers between 0 and 9. Print its shape and number of dimensions.

In [24]:
arr1 = np.random.randint(0,10, size = (2,3,4))
print(f"Array :- {arr1}")
print(f"Shape :- {arr1.shape}")
print(f"N dim :- {arr1.ndim}")

Array :- [[[8 7 4 1]
  [4 7 9 8]
  [8 0 8 6]]

 [[8 7 0 7]
  [7 2 0 7]
  [2 2 0 4]]]
Shape :- (2, 3, 4)
N dim :- 3


### **B3.** Given `arr = np.arange(1, 25)`, reshape it into a 3D array of shape `(2, 3, 4)`.

In [27]:
arr2 = np.arange(1,25)
print(f"Array :- {arr2}")
print(f"After reshape :- {arr2.reshape((2,3,4))}")

Array :- [ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24]
After reshape :- [[[ 1  2  3  4]
  [ 5  6  7  8]
  [ 9 10 11 12]]

 [[13 14 15 16]
  [17 18 19 20]
  [21 22 23 24]]]


## Section C: Indexing & Slicing — 1D

#### Given: `arr = np.array([12, 45, 7, 89, 34, 23, 67, 5, 90, 15])`

##### **C1.** Get the first 3 elements.

##### **C2.** Get the last 3 elements.

##### **C3.** Get every 2nd element starting from index 1.

##### **C4.** Reverse the array.

##### **C5.** Get all elements greater than 30 (boolean indexing).

##### **C6.** Get the elements at indices 0, 3, and 7 (fancy indexing).

In [ ]:
arr3 = np.array([12, 45, 7, 89, 34, 23, 67, 5, 90, 15])
print(f"Array : {arr3}")
print(f"C1 : {arr3[:3]}")
print(f"C1 : {arr3[-3:]}")
print(f"C3 : {arr3[::2]}")
print(f"C4 : {arr3[::-1]}")
print(f"C5 : {arr3[arr3>30]}")
print(f"C6 : {arr3[::3]}")

Array : [12 45  7 89 34 23 67  5 90 15]
C1 : [12 45  7]
C1 : [ 5 90 15]
C3 : [12  7 34 67 90]
C4 : [15 90  5 67 23 34 89  7 45 12]
C5 : [45 89 34 67 90]
C6 : [12 89 67 15]


## Section D: Indexing & Slicing — 2D

##### Given: ```python arr2d = np.array([[4, 8, 15, 16], [23, 42, 6, 9],[11, 20, 13, 7], [1, 5, 99, 3]])```

##### **D1.** Get the element at row 2, column 3.

##### **D2.** Get the entire 3rd row (index 2).

##### **D3.** Get the entire last column.

##### **D4.** Get the sub-matrix formed by the first 2 rows and last 2 columns.

##### **D5.** Get all elements greater than 10.

##### **D6.** Replace every element greater than 50 with `0`.

## Section E: EDA-Style Statistics

##### Given: `data = np.array([23, 45, 12, 67, 34, 89, 21, 56, 78, 90, 15, 33])`

##### **E1.** Find the mean, median, and standard deviation.

##### **E2.** Find the 25th, 50th, and 75th percentiles.

##### **E3.** Compute the z-score for every value: `(x - mean) / std`.

##### **E4.** Using the z-scores from E3, filter out values whose absolute z-score is greater than 1.5 (these are potential outliers).

##### **E5.** Normalize `data` to a 0–1 range using min-max scaling: `(x - min) / (max - min)`.

##### **E6.** Find the number of unique values and their counts using `np.unique`.

## Section F: Handling Missing Values

##### Given: `data = np.array([10, np.nan, 25, 40, np.nan, 55, 30])`

##### **F1.** Count how many `NaN` values are in the array.

##### **F2.** Compute the mean while ignoring `NaN` values.

##### **F3.** Replace all `NaN` values with the mean of the non-NaN values.

## Section G: Random Sampling

##### **G1.** Generate a 3x3 matrix of values sampled from the standard normal distribution using `np.random.randn`.

##### **G2.** Generate 5 random floats between 0 and 1 using `np.random.random_sample`.

##### **G3.** Simulate rolling a die 20 times (random integers 1–6) and find how many times each face (1–6) appeared. (hint: `np.unique` with `return_counts=True`)

##### **G4.** Create a random 5x5 matrix of integers between 1–100, then find its row-wise mean and column-wise mean (hint: use the `axis` parameter in `np.mean`).


## Section H: Mini Challenge (Combine Everything)

###### You're given a simulated dataset of 50 students' exam scores:

```python
np.random.seed(1)
scores = np.random.randint(30, 100, size=50)
```

###### Do the following:
###### 1. Print the mean, median, and standard deviation of scores.
###### 2. Find how many students scored above 75.
###### 3. Find how many students scored below 40 (potentially at-risk students).
###### 4. Normalize the scores to a 0–1 range.
###### 5. Find the top 5 highest scores using slicing on a sorted array.
###### 6. Bucket the scores into 5 bins and print the frequency count in each bin using `np.histogram`.